---
kind: pipeline
type: kubernetes
name: default

steps:
  # - name: precheck
  #   image: orlandobrea/andes-check-image-exist:latest
  #   pull: always
  #   environment:
  #     # REGISTRY_URL: registry.hub.docker.com
  #     IMAGE_NAME: orlandobrea/dashboard-migracion-sips-be
  #     TAG: ${DRONE_BRANCH}-${DRONE_COMMIT_SHA}
  #     REGISTRY_USER: 
  #       from_secret: REGISTRY_USER
  #     REGISTRY_PASSWORD:
  #       from_secret: REGISTRY_PASSWORD
  # Test

  # Release
  - name: release
    image: docker:dind
    commands:
      - npm install
      - npx semantic-release
  - name: build
    image: plugins/docker  
    when:
      status:
        - failure    
    settings:
      debug: false
      username: 
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASSWORD
      # registry: ${DOCKER_REGISTRY_URL}
      repo: orlandobrea/dashboard-migracion-sips-be 
      tags: ["${DRONE_BRANCH}", "${DRONE_BRANCH}-${DRONE_COMMIT_SHA}"]
      # insecure: true

      
# Params example:
# DRONE_BRANCH: master
# DOCKER_REGISTRY_URL: registry.192-168-68-2.nip.io:30443

